version: "3.7"
services:
  postgres:
    image: postgres:13
    networks: 
      - broker-connect
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=commondb
    volumes:
      - /storage/docker/postgres-latest

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - broker-connect
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    networks: 
      - broker-connect
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAKFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092, PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
  redis:
    image: bitnami/redis:latest
    networks: 
      - broker-connect
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD: password
    ports:
      - 6379:6379
  
  mockServer:
    image: mockserver/mockserver:5.14.0
    networks: 
      - broker-connect
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_MAX_EXPECTATIONS: 100
      MOCKSERVER_MAX_HEADER_SIZE: 8192

  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: dbcommon
      MYSQL_USER: admin
      MYSQL_PASSWORD: pwd
    ports:
      - 3306:3306
    networks:
      - broker-connect
    
      
networks: 
  broker-connect: 
    driver: bridge  
